# Generated by Django 4.2.4 on 2023-09-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Pedidos', '0002_alter_clientes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(max_length=15, verbose_name='su telefono'),
        ),
    ]
