# Generated by Django 4.2.4 on 2023-09-12 03:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Pedidos', '0003_alter_clientes_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='seccion',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
